work on blocks in the layout
js-tasks-ru/htmlcss-20230411_aleksandr-pupkov1991 pull request #9
Opened 2023-05-09 17:04 UTC by aleksandrpupkov

2023-05-09 17:05 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-05-11 15:05 UTC, GSemikozov requested changes

2023-05-11 15:05 UTC, GSemikozov commented on components/main/promo.css
> +    margin-top: 30px;
а для чего этот марджин? если чтобы отступить от соседней карты сверху, то - как задаем отступы между картами на одном уровне?

2023-05-18 21:40 UTC, GSemikozov approved these changes

2023-05-18 21:40 UTC, jsru commented
К сожалению, PR не может быть замержен, GSemikozov вероятно сможет помочь.

2023-05-18 21:41 UTC, GSemikozov approved these changes

2023-05-18 21:41 UTC, merged